import type { Metadata } from "next";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "../../components/Header";
import { SanityLive } from "@/sanity/lib/live";
import { Montserrat } from "next/font/google";
import Footer from "@/components/Footer";

const monserrat = Montserrat({
  subsets: ["latin"],
  weight: ["100", "200", "400", "700", "900"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Bare Botanics Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <body className={`${monserrat.variable} antialiased`}>
          <Header />
          <main>{children}</main>
          <Footer />
          <SanityLive />
        </body>
      </html>
    </ClerkProvider>
  );
}
